version: "3.7"

services:
    # image project
    app:
        container_name: Buzz
        build:
            args:
                user: fabricio
                uid: 1000
            context: .
            dockerfile: Dockerfile
        image: especializati/laravel9-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel-9

    # nginx
    nginx:
        container_name: nginxBuzz
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel-9

    # db mysql
    mysql:
        container_name: mysqlBuzz
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: buzzvel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: root
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3385:3306"
        networks:
            - laravel-9

    # queue
    queue:
        container_name: queueBuzz
        image: especializati/laravel9-app
        restart: unless-stopped
        # command: "php artisan queue:generate"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel-9

    # redis
    redis:
        container_name: redisBuzz
        image: redis:latest
        networks:
            - laravel-9

networks:
    laravel-9:
        driver: bridge
